### ISSUE TITLE
Handling Detailed Output from Unit Tests

### ISSUE THREAD

**Issue by rosenbrockc** [rosenbrockc/ci#1]
The initial CI server is almost ready. However, I just realized that we need to discuss one more aspect. So far, I programmed the server to keep track of the output from `stdout` when running each unit test. That output is kept in memory until the wiki page with the unit test details is created. My original idea was to upload the contents of `stdout` for each test to a file on the wiki and then just link to it from the test results page.

That still seems like a viable possibility except that for some of the unit tests the output can be quite large. Do we place limitations on the size of the files we want to upload? If fortpy handles the unit testing, it provides summary information and will write out compilation errors or warnings and that output is usually small. But what about output from other programs? For example, the Wang Landau in UNCLE once produced a file that was 135GB!

Question: if the files are larger than 1MB, do we upload only part of them? If so, which part? If not, do we just say the file was too big? Do we remove it from the server then, or move it to some archive?

**Comment by glwhart** [comment]
All good questions. I think that we should limit output that is posted to the server. If there are differences, maybe we should post "diffs" if they are less than 1MB or something. Maybe just the summaries are enough. If there is anything amiss, then we are going to look into it. Not sure that there will be too much utility in having _everything_ posted to the server in that case. 

So as I'm writing and thinking, I think concise summaries are enough to post to the server. If everything passes, that's all we need to know probably. If not, having a bunch of information posted won't really help much, because we are going to go back and look in the tests and poke around...

**Comment by rosenbrockc** [comment]
Andrew and I had a conversation and came up with the same conclusion. We will limit the unit testing details to be a summary less than 1MB. The person designing the unit tests should analyze the output from their software and create a summarized version with the most important points. If there is a problem, the developer will probably start playing with the software and running the unit tests by hand at that point.

Thank-you for your input.

**Comment by glwhart** [comment]
Loving this new workflow! (Using github to track/comment/etc)
